import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { Screen } from "@/src/components/Screen";
import { Card } from "@/src/components/Card";
import { colors } from "@/src/theme";
import { apiFetch } from "@/src/services/api";

export default function AssignmentsScreen(){
  const[items,setItems]=useState<any[]>([]),[title,setTitle]=useState(""),[course,setCourse]=useState("General"),[error,setError]=useState("");
  async function load(){try{setItems(await apiFetch("/assignments"));}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[]);
  async function add(){if(!title.trim())return;try{await apiFetch("/assignments",{method:"POST",body:JSON.stringify({title:title.trim(),course:course.trim()||"General",progress:0,status:"pending"})});setTitle("");await load();}catch(e:any){setError(e.message)}}
  async function setProgress(item:any,value:number){const progress=Math.max(0,Math.min(100,value));await apiFetch(`/assignments/${item.id}`,{method:"PATCH",body:JSON.stringify({...item,progress,status:progress===100?"completed":"pending"})});await load()}
  async function remove(id:number){await apiFetch(`/assignments/${id}`,{method:"DELETE"});await load()}
  return <Screen><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.title}>Assignments</Text><Text style={styles.subtitle}>Track coursework and give Smith accurate planning context.</Text><Card><TextInput style={styles.input} value={title} onChangeText={setTitle} placeholder="Assignment title" placeholderTextColor={colors.muted}/><TextInput style={styles.input} value={course} onChangeText={setCourse} placeholder="Course unit" placeholderTextColor={colors.muted}/><Pressable style={styles.button} onPress={add}><Text style={styles.buttonText}>Add assignment</Text></Pressable>{!!error&&<Text style={styles.error}>{error}</Text>}</Card><Text style={styles.section}>Current</Text>{items.map(i=><Card key={i.id} style={styles.item}><Text style={styles.itemTitle}>{i.title}</Text><Text style={styles.meta}>{i.course} · {i.progress||0}% complete</Text><View style={styles.actions}><Pressable style={styles.small} onPress={()=>setProgress(i,(i.progress||0)+25)}><Text style={styles.smallText}>+25%</Text></Pressable><Pressable style={styles.small} onPress={()=>setProgress(i,100)}><Text style={styles.smallText}>Complete</Text></Pressable><Pressable onPress={()=>remove(i.id)}><Text style={styles.delete}>Delete</Text></Pressable></View></Card>)}{!items.length&&<Text style={styles.meta}>No assignments saved yet.</Text>}</Screen>}
const styles=StyleSheet.create({back:{color:colors.primary,fontWeight:"800",marginBottom:12},title:{color:colors.text,fontSize:28,fontWeight:"900"},subtitle:{color:colors.muted,lineHeight:20,marginTop:5,marginBottom:18},input:{backgroundColor:colors.surface2,color:colors.text,borderWidth:1,borderColor:colors.border,borderRadius:13,padding:13,marginBottom:10},button:{backgroundColor:colors.primary,padding:14,borderRadius:13,alignItems:"center"},buttonText:{color:"#061426",fontWeight:"900"},error:{color:colors.danger,marginTop:10},section:{color:colors.text,fontSize:18,fontWeight:"800",marginVertical:15},item:{marginBottom:10},itemTitle:{color:colors.text,fontWeight:"800",fontSize:16},meta:{color:colors.muted,marginTop:5},actions:{flexDirection:"row",gap:9,alignItems:"center",marginTop:12},small:{paddingVertical:8,paddingHorizontal:11,borderRadius:10,backgroundColor:colors.surface2},smallText:{color:colors.primary,fontWeight:"800",fontSize:12},delete:{color:colors.danger,fontWeight:"800",fontSize:12}});
